export const plantsList = [
    {
        img: require('./images/aloe_vera.png'),
        name: 'Aloe vera',
        watering: '1 - 2 times weekly',
        soil_type: 'Well-drained commercial potting mix',
        sun_exposure: 'Bright, indirect sun',
        native_climate: 'Southern and eastern Africa',
        plant_type: 'Succulent, Herb, Perennial',
        bloom: 'Summer',
        mature_height: '1 - 2 feet tall',
    },
    {
        img: require('./images/cactus.png'),
        name: 'Cactus',
        watering: 'Every week or two',
        soil_type: 'Well-drained, sandy',
        sun_exposure: 'Full sun',
        native_climate: 'North America, South America',
        plant_type: 'Succulent, Perennial',
        bloom: 'Summer',
        mature_height: '1-96 inches tall, 2-30 inches wide depending on species and cultivar',
    },
    {
        img: require('./images/orchids.png'),
        name: 'Orchids',
        watering: '1 - 2 times weekly',
        soil_type: 'Well-drained',
        sun_exposure: 'Partial',
        native_climate: 'Central America, South America',
        plant_type: 'Perennial',
        bloom: 'Spring, fall',
        mature_height: '3 - 24 in tall and wide',
    },
    {
        img: require('./images/dahlia.png'),
        name: 'Dahlia',
        watering: '1 of water every week',
        soil_type: 'Loamy, Well-Drained',
        sun_exposure: 'Full',
        native_climate: 'North America, Central America',
        plant_type: 'Perennial',
        bloom: 'Summer, Fall',
        mature_height: '1-6 feet. tall, 1-3 feet. wide',
    },
    {
        img: require('./images/easter_lily.png'),
        name: 'Easter lily',
        watering: 'Every 3 days',
        soil_type: 'Loamy, well-drained',
        sun_exposure: 'Full, partial',
        native_climate: 'Southern and eastern Africa',
        plant_type: 'Perennial',
        bloom: 'Summer',
        mature_height: '2 - 3 ft. tall, 1 ft. wide',
    },
    {
        img: require('./images/fairy_duster.png'),
        name: 'Fairy Duster',
        watering: 'Every 1-2 weeks ',
        soil_type: 'Sandy, well-drained',
        sun_exposure: 'Full sun',
        native_climate: 'California, Arizona, New Mexico, Texas and Mexico',
        plant_type: 'Perennial, Shrub',
        bloom: 'Spring',
        mature_height: '1 - 2 feet tall',
    },
]

export const options = ['Select plant type','Perennial', 'Shrub', 'Succulent', 'Herb', 'All']